version: "3"

tasks:
  gen-ebpf:
    sources:
      - "bpf/*.c"
    generates:
      - "*.o"
    cmds:
      - go generate
  build:
    deps:
      - gen-ebpf
    sources:
      - "*.go"
      - "*.o"
    generates:
      - "build/{{.BIN_NAME}}"
    cmds:
      - go build -o build/{{.BIN_NAME}}
  up:
    deps:
      - build
    cmds:
      - sudo ./scripts/tear_up.sh
      - sudo ./scripts/insert_srfunc_route.sh
      - sudo ./scripts/insert_ebpf_routes.sh
  down:
    cmds:
      - sudo ./scripts/tear_down.sh

vars:
  BIN_NAME: ebpf-test
