version: "3"

tasks:
  gen-ebpf:
    sources:
      - bpf/*.c
    generates:
      - "**/*.o"
    cmd: go generate ./...
  build:
    deps:
      - gen-ebpf
    generates:
      - build/{{.BIN_NAME}}
    sources:
      - "**/*.go"
    cmd: go build -o build/{{.BIN_NAME}}
  up:
    cmd: sudo ./scripts/tear_up.sh
  up-sr:
    cmd: sudo ./scripts/insert_srfunc_route.sh
  start:
    deps:
      - build
    cmd: sudo ./scripts/insert_ebpf_routes.sh
    interactive: true
  down:
    cmd: sudo ./scripts/tear_down.sh

vars:
  BIN_NAME: lb-proposal
